apiVersion: apps/v1
kind: Deployment
metadata:
  name: yannick
  namespace: dev
  labels:
    app: app1
spec:
   replicas: 4
   selector:
     matchLabels:
       app: app1
   template:
     metadata:
       labels:
          app: app1
     spec:
       containers:
       - name: yannick
         image: yannmanux/yannick-image2
         ports:
         - containerPort: 80
                                                                                                            
